#index:
#    path: /
#    controller: App\Controller\DefaultController::index


index:
  path: /
  controller: App\Controller\PropertyController::index

add:
  path: /new
  controller: App\Controller\PropertyController::add

store:
  path: /store
  controller: App\Controller\PropertyController::storeProperty